# Generated by Django 5.2.2 on 2025-06-26 10:20

import django.db.models.deletion
import ox.utils.models.color
import uuid
from django.conf import settings
from django.db import migrations, models

from ox_erp.contacts import utils


def forward_sync(apps, schema_editor):
    utils.sync_user_contacts(apps, schema_editor.connection.alias)
    utils.ContactListSynchronizer().sync()


def backward_sync(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("ox_locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name="Email")),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("iban", models.CharField(max_length=40, verbose_name="IBAN")),
                ("bic", models.CharField(max_length=11, verbose_name="SWIFT/BIC")),
                ("address", models.CharField(max_length=128, verbose_name="Address")),
                ("bank_name", models.CharField(max_length=128, verbose_name="Bank Name")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
                    ),
                ),
            ],
            options={
                "verbose_name": "IBAN Account",
                "verbose_name_plural": "IBAN Accounts",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("street", models.CharField(max_length=128, verbose_name="Street")),
                ("street_2", models.CharField(blank=True, default="", max_length=128, verbose_name="Street 2")),
                ("number", models.CharField(max_length=16, verbose_name="Number")),
                ("box", models.CharField(blank=True, default="", max_length=16, verbose_name="Box")),
                ("postcode", models.PositiveIntegerField(verbose_name="Postcode")),
                ("city", models.CharField(max_length=128, verbose_name="City")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country"
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="ContactList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("color", ox.utils.models.color.ColorField(blank=True, max_length=7, null=True, verbose_name="Color")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "is_subscription",
                    models.BooleanField(
                        default=False,
                        help_text="This list is used for mailing-lists. It allows contacts to unsubscribe from the list among other things.",
                        verbose_name="Subscription list",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        help_text="This list is related to a group",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_list",
                        to="auth.group",
                        verbose_name="Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact List",
                "verbose_name_plural": "Contact Lists",
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_lists",
            field=models.ManyToManyField(
                blank=True, related_name="contacts", to="ox_contacts.contactlist", verbose_name="Lists"
            ),
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "default_related_name": "email_set",
            },
        ),
        migrations.CreateModel(
            name="OrganisationType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("code", models.CharField(blank=True, default="", max_length=8, verbose_name="Code")),
                ("abbreviation", models.CharField(blank=True, default="", max_length=32, verbose_name="Abbreviation")),
                ("language_code", models.CharField(blank=True, default="", max_length=4, verbose_name="Language Code")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_locations.country", verbose_name="Country"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Form",
                "verbose_name_plural": "Company Forms",
            },
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "kind",
                    models.SmallIntegerField(
                        choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                        default=0,
                        verbose_name="Kind",
                    ),
                ),
                ("number", models.CharField(max_length=32, verbose_name="Phone")),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone",
                "verbose_name_plural": "Phones",
            },
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ox_contacts.contact",
                    ),
                ),
                ("color", ox.utils.models.color.ColorField(blank=True, max_length=7, null=True, verbose_name="Color")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=256, null=True, verbose_name="Description"),
                ),
                ("short_name", models.CharField(blank=True, max_length=32, null=True, verbose_name="Short Name")),
                ("reference", models.CharField(blank=True, default="", max_length=32, verbose_name="Reference Number")),
                ("vat", models.CharField(blank=True, max_length=32, null=True, verbose_name="VAT")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ox_locations.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ox_contacts.organisationtype",
                        verbose_name="Organisation Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
            },
            bases=("ox_contacts.contact", models.Model),
        ),
        migrations.AddField(
            model_name="contactlist",
            name="organisation",
            field=models.OneToOneField(
                blank=True,
                help_text="This list is related to an organisation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_list",
                to="ox_contacts.organisation",
                verbose_name="Organisation",
            ),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ox_contacts.contact",
                    ),
                ),
                ("first_name", models.CharField(default="", max_length=64, verbose_name="First name")),
                ("last_name", models.CharField(default="", max_length=64, verbose_name="Last name")),
                (
                    "organisations",
                    models.ManyToManyField(
                        blank=True, related_name="persons", to="ox_contacts.organisation", verbose_name="Organisations"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="This contact is related to a user of the plateform",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
            bases=("ox_contacts.contact",),
        ),
        migrations.RunPython(forward_sync, backward_sync),
    ]
