# Generated by Django 5.2.9 on 2025-12-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationtype",
            name="abbreviation",
            field=models.CharField(blank=True, default="", max_length=512, verbose_name="Abbreviation"),
        ),
        migrations.AlterField(
            model_name="organisationtype",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
    ]
