# Generated by Django 5.2.9 on 2025-12-18 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models
from ox.utils.models import get_model


def forward_sync(apps, schema_editor):
    Person = get_model("ox_contacts.person")
    for person in Person.objects.all():
        person.name = person.full_name
        person.save(update_fields=["name"])


def backward_sync(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0002_alter_organisationtype_abbreviation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="contact_lists",
        ),
        migrations.RemoveField(
            model_name="organisation",
            name="name",
        ),
        migrations.AddField(
            model_name="contact",
            name="name",
            field=models.CharField(default="", max_length=64, verbose_name="Name"),
            preserve_default=False,
        ),
        migrations.RunPython(forward_sync, backward_sync),
        migrations.AlterField(
            model_name="address",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Info kind",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Info kind",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Info kind",
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="kind",
            field=models.SmallIntegerField(
                choices=[(0, "Main"), (1, "Professional"), (2, "Home"), (3, "Legal"), (16, "Other")],
                default=0,
                verbose_name="Info kind",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Invitation Send"), (2, "Subscribed"), (3, "Unsubscribed")],
                        default=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_contacts.contact", verbose_name="Contact"
                    ),
                ),
                (
                    "contact_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ox_contacts.contactlist",
                        verbose_name="Contacts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
            },
        ),
        migrations.AddField(
            model_name="contactlist",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_lists",
                through="ox_contacts.Subscription",
                through_fields=("contact_list", "contact"),
                to="ox_contacts.contact",
                verbose_name="Contacts",
            ),
        ),
    ]
