# Generated by Django 5.2.2 on 2026-01-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0003_remove_contact_contact_lists_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationtype",
            options={
                "verbose_name": "Organisation Type",
                "verbose_name_plural": "Organisation Types",
            },
        ),
        migrations.AlterField(
            model_name="subscription",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="ox_contacts.contact",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="contact_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="ox_contacts.contactlist",
                verbose_name="Contacts",
            ),
        ),
    ]
