# Generated by Django 5.2.2 on 2025-06-26 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("code", models.CharField(max_length=3, verbose_name="Code")),
                ("numeric", models.CharField(max_length=3, verbose_name="Numeric code")),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name="Decimals"),
                ),
                ("is_iso", models.BooleanField(verbose_name="Is ISO")),
                ("valid_to", models.DateField(blank=True, null=True, verbose_name="Withdrawal Date")),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("code", models.CharField(db_index=True, max_length=2, verbose_name="Code")),
                ("code_3", models.CharField(db_index=True, max_length=3, verbose_name="Code 3")),
                (
                    "continent",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Africa"),
                            (2, "Antartica"),
                            (3, "Asia"),
                            (4, "Europe"),
                            (5, "North America"),
                            (6, "Oceania"),
                            (7, "South America"),
                        ],
                        verbose_name="Continent",
                    ),
                ),
                ("phone", models.PositiveIntegerField(verbose_name="Phone prefix")),
                ("iban_sample", models.CharField(blank=True, max_length=42, null=True, verbose_name="Sample IBAN")),
                ("iban_length", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="IBAN length")),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ox_locations.currency",
                        verbose_name="Currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
