# Generated by Django 5.2.2 on 2025-12-19 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="iban_sample",
            field=models.CharField(blank=True, max_length=42, null=True, verbose_name="IBAN Sample"),
        ),
        migrations.AlterField(
            model_name="country",
            name="phone",
            field=models.CharField(db_index=True, default="", max_length=6, verbose_name="Phone"),
        ),
        migrations.CreateModel(
            name="PhonePrefix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name="Reference")),
                ("prefix", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_prefixes",
                        to="ox_locations.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phone Prefix",
                "verbose_name_plural": "Phone Prefixes",
            },
        ),
    ]
