# Generated by Django 5.2.2 on 2025-12-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_locations", "0002_alter_country_iban_sample_alter_country_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneprefix",
            name="prefix",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
