# Generated by Django 5.2.2 on 2025-12-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ox_locations", "0003_alter_phoneprefix_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="phone",
        ),
    ]
