# Generated by Django 5.2.2 on 2025-12-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_locations", "0004_remove_country_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneprefix",
            name="prefix",
            field=models.CharField(
                db_index=True,
                help_text='Contains international and optional area code, without "+" or "00".',
                max_length=10,
                verbose_name="Prefix",
            ),
        ),
    ]
