# Generated by Django 5.2.9 on 2025-12-06 14:35

import django.db.models.deletion
import ox.apps.content.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caps", "0001_initial"),
        ("ox_contacts", "0002_alter_organisationtype_abbreviation_and_more"),
        ("ox_files", "0001_initial"),
        ("ox_mails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, verbose_name="Id")),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Draft"), (1, "Sending"), (2, "Sent"), (3, "Error")],
                        default=0,
                        verbose_name="State",
                    ),
                ),
                ("context", models.JSONField(default=dict, verbose_name="Context")),
                (
                    "subject",
                    models.TextField(
                        default="", help_text="When provided, overrides template's content", verbose_name="Subject"
                    ),
                ),
                (
                    "content",
                    ox.apps.content.models.RichTextField(
                        default="", help_text="When provided, overrides template's content.", verbose_name="Message"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ox_mails.mailaccount", verbose_name="Account"
                    ),
                ),
                (
                    "attachments",
                    models.ManyToManyField(related_name="+", to="ox_files.file", verbose_name="Attach files"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="caps.agent", verbose_name="Owner"
                    ),
                ),
                (
                    "recipient_lists",
                    models.ManyToManyField(to="ox_contacts.contactlist", verbose_name="Recipient lists"),
                ),
                ("recipients", models.ManyToManyField(to="ox_contacts.contact", verbose_name="Recipients")),
            ],
            options={
                "verbose_name": "Contact Mail",
                "verbose_name_plural": "Contact Mails",
            },
        ),
        migrations.CreateModel(
            name="ContactMailAccess",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name="Id")),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        help_text="Defines an expiration date after which the access is not longer valid.",
                        null=True,
                        verbose_name="Expiration",
                    ),
                ),
                ("grants", models.JSONField(blank=True, verbose_name="Granted permissions")),
                (
                    "emitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Emitter",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived",
                        to="ox_contacts_mails.contactmailaccess",
                        verbose_name="Origin",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="caps.agent",
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="ox_contacts_mails.contactmail",
                        verbose_name="Target",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "proxy": False,
            },
        ),
    ]
