# Generated by Django 5.2.2 on 2026-01-12 13:38

import ox.apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts", "0004_alter_organisationtype_options_and_more"),
        ("ox_contacts_mails", "0001_initial"),
        ("ox_files", "0002_alter_folder_is_sync_filecomment_foldercomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmail",
            name="attachments",
            field=models.ManyToManyField(related_name="+", to="ox_files.file", verbose_name="Attached files"),
        ),
        migrations.AlterField(
            model_name="contactmail",
            name="content",
            field=ox.apps.content.models.RichTextField(default="", verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="contactmail",
            name="recipient_lists",
            field=models.ManyToManyField(to="ox_contacts.contactlist", verbose_name="Contacts Lists"),
        ),
        migrations.AlterField(
            model_name="contactmail",
            name="subject",
            field=models.TextField(default="", verbose_name="Subject"),
        ),
    ]
