# Generated by Django 5.2.2 on 2026-01-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ox_contacts_mails", "0002_alter_contactmail_attachments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmailaccess",
            options={
                "verbose_name": "Contact Mail",
                "verbose_name_plural": "Contact Mails",
            },
        ),
    ]
